syntax = "proto3";

package scheduler;

option go_package = "github.com/mmirzabaig/uptime-monitor/gen/scheduler";

service Scheduler {
    rpc CreateMonitor(CreateMonitorRequest) returns (CreateMonitorResponse);
    rpc RegisterWorker(RegisterWorkerRequest) returns (RegisterWorkerResponse);
}

message CreateMonitorRequest {
    string url = 1;
    int64 interval = 2;
    int64 timeout = 3;
}

message CreateMonitorResponse {
    string id = 1;
}

message RegisterWorkerRequest {
    string address = 1;
}

message RegisterWorkerResponse {
    string id = 1;
}